ARG PORT
ARG DB_HOST 
ARG DB_PORT
ARG DB_USER
ARG DB_NAME
ARG SCHEMA
ARG TABLE_NAME 
ARG VITE_SERVER_URL

FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .
ENV PORT=${PORT}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USER=${DB_USER}
ENV DB_NAME=${DB_NAME}
ENV SCHEMA=${SCHEMA}
ENV TABLE_NAME=${TABLE_NAME}
ENV VITE_SERVER_URL=${VITE_SERVER_URL}
EXPOSE ${PORT}

CMD ["npm", "run", "start"]
